### ISSUE TITLE
Documentation incomplete for "publish" function override

### ISSUE THREAD

**Issue by joeblynch** [wmbenedetto/turbine.js#10]
The documentation states that the publish function, when overridden, takes 2 parameters: a string and an object. In actuality the first param might be an array of strings, and a 3rd param of a callback function is passed. If this callback function is not called by the overridden publish function then the Turbine workflow halts in some situations.

For now, I'll have my publish override accept either a event name string or an array of events name strings and a callback function. Perhaps the logic of iterating through an array of events name strings, and calling the callback after publish, shouldn't be overridden by the user supplied publish override function, and instead the user supplied publish function should be called once for each event and the callback called by Turbine afterwards?

**Comment by wmbenedetto** [comment]
Thanks for the feedback. You're right that a third callback param can be passed, and that's not in the documentation. I will update the docs to make that explicit.

However, Turbine itself shouldn't freeze up if this callback function is never called. Your _app_ may freeze if, for example, the callback is supposed to publish a message that Turbine is waiting for. If the callback is never called, the message is never published, and Turbine just keeps waiting until it times out.

If that's not what you're seeing, and Turbine itself is actually stalling, please give me a specific example so I can try to reproduce the issue. There may be a bug that I'm not seeing right now.

**Comment by joeblynch** [comment]
Here's an [example of this behavior on jsFiddle](http://jsfiddle.net/Nkbg9/). In this case, we should be seeing a "RequestGameWithForceLogout" message published by Turbine after it receives the "AlreadyStreaming|ForceLogout" message, however this doesn't happen unless you uncomment the callback call at line 60.

**Comment by wmbenedetto** [comment]
I just found the bug that was causing this issue. The publish() function supplied in the initObj was overriding Turbine's own publish() method instead of the internal pubsub.publish() function. 

Turbine's publish() method does exactly what you suggested in your original post: it iterates over an array of messages, and executes the callback as needed. But because that was being overwritten, you were being forced to replicate that functionality yourself in your own publish() function.

The documentation is actually correct -- your publish method should receive 2 params: a string and an object. It should not receive an array or a callback function. I'll be pushing a fix shortly.

**Comment by wmbenedetto** [comment]
The fix (along with a bunch of new features) is up on the develop branch now, and your jsFiddle example seems to be working as expected. I'll be pushing it to master once I write some new unit tests for the new features.
